### ISSUE TITLE
PointList not updated after clearing the previous paths.

### ISSUE THREAD

**Issue by charan-r** [mzachari/agm-example#5]
Hi,
    I found an issue while working on your code. on initial refresh, we can draw a polygon and I'm getting the pointList, the issue happens when the user clears the previous path and created the new polygon, in that case, pointList is not updating, pls have a look on this, Thanks in advance!!!

**Comment by mzachari** [comment]
Sure, will check and get back!

**Comment by mzachari** [comment]
Fix merged by commit "Fixing issue: PointList not updated after clearing the previous paths.". Please verify and get back!
